version: '3'

services:
  web-app:
    restart: always
    build:
      context: .
    command: bash -c '
               python src/manage.py migrate;
               python src/manage.py createsuperuserwithpassword --username admin --password admin --email admin@gmail.com;
               python src/manage.py runserver 0.0.0.0:8000;
            '
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - docker-compose.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: